# Data acquisition

This notebook builds the dataset and gathers every structure the analysis uses. Candidate proteins are
taken from public tables (SIFTS, the wwPDB method and resolution indexes, and UniProt) and filtered by a
fixed set of rules, after which one chain is chosen for each experimental method. The experimental
structures are downloaded from the RCSB PDB and the AlphaFold2 models from the AlphaFold Database; the
OpenFold3 models are predicted through the NVIDIA NIM service, with a multiple sequence alignment for
every protein. Files already on disk are not downloaded or predicted again.

**Input:** network access and an NVIDIA NIM API key, set as `NIM_API_KEY=nvapi-…` in a `.env` file at the
repository root (keys are issued at https://build.nvidia.com/openfold/openfold3).  
**Output:** `proteins.csv`, the structure files in `data/` and `results/dataset_selection_counts.csv`.

## Setup

In [13]:
import sys, os, json
import pandas as pd
from dotenv import load_dotenv
from IPython.display import display

if os.path.basename(os.getcwd()) == "notebooks":
    os.chdir("..")
sys.path.insert(0, ".")

from src.downloader import (
    download_rcsb,
    download_alphafold2,
    fetch_uniprot_sequence,
    fetch_msa,
    predict_openfold3,
)
from src.parser import load_structure, get_ca_coords_and_seq
from src.metadata import extract_metadata
import src.dataset as ds

load_dotenv()

nim_key_loaded = bool(os.environ.get("NIM_API_KEY"))
print(f"NIM_API_KEY found: {nim_key_loaded}")
if not nim_key_loaded:
    print("  Add NIM_API_KEY=nvapi-... to a .env file at the repo root.")

NIM_API_KEY found: True

In [14]:
DATA_DIR = "data"
EXP_DIR = os.path.join(DATA_DIR, "experimental")
AF2_DIR = os.path.join(DATA_DIR, "alphafold2")
OF3_DIR = os.path.join(DATA_DIR, "openfold3")

for d in [EXP_DIR, AF2_DIR, OF3_DIR]:
    os.makedirs(d, exist_ok=True)
    print(f"  {d}")

proteins = pd.read_csv("proteins.csv", dtype=str, keep_default_na=False)
print(f"\n{len(proteins)} proteins currently in manifest:")
display(proteins[["protein_name", "uniprot_id", "pdb_xray", "pdb_nmr", "pdb_cryoem"]])

  data/experimental
  data/alphafold2
  data/openfold3

151 proteins currently in manifest:

,protein_name,uniprot_id,pdb_xray,pdb_nmr,pdb_cryoem
0,Type IV pilin PilE1,A0A0B7GU52,,6I2O,8PFB
1,Toxin co-regulated pilus biosynthesis protein ...,A0AAI7ZGD2,,2L4W,6GYB
2,ATP synthase epsilon chain (B1MLW3),B1MLW3,,7VIL,9VKR
3,Type II secretion system core protein G,E0SM38,,29JD,11ME
4,"Acyl carrier protein, mitochondrial",O14561,6ODD,2DNW,7OF0
...,...,...,...,...,...
146,Dynein axonemal light chain 1,Q9XHH2,5YXM,1DS9,8GLV
147,Cofilin-2 (Q9Y281),Q9Y281,,7M0G,9Y9P
148,Ribosome maturation protein SBDS,Q9Y3A5,,2KDO,5AN9
149,Peptidyl-prolyl cis-trans isomerase-like 1,Q9Y3C6,2X7K,1XWN,9S2E
150,Phage protein,V9H5N5,,8JB9,8HJ4

---
## Dataset selection

`proteins.csv` is generated here, not edited by hand. The rules, in order:

| # | Rule | Why |
|---|------|-----|
| 0 | Quality limits: X-ray ≤ `MAX_XRAY` Å, cryo-EM ≤ `MAX_EM` Å, NMR all | poorly determined structures are not used as references |
| 1 | The protein has **NMR and cryo-EM** structures | the comparison needs several methods per protein; NMR is the scarcest method (counts below), so the set is built outward from it, and cryo-EM is the second method of the topic. X-ray is added where it exists |
| 2 | One mature chain in UniProt (no polyprotein) | experiment and prediction must describe the same molecule |
| 3 | Mature chain length within `LENGTH` | enough residues for the metrics; the size range NMR can solve; prediction memory grows with N² and time with N³ |
| 4 | An NMR chain **and** a cryo-EM chain each model ≥ `MIN_COVERAGE` of the mature chain | the metrics summarise whole chains, so residues missing on one side would be measured as structural difference (notebook 03 measures how much) |
| 5 | An AlphaFold DB model exists | needed for the comparison |

Then **one chain per method** is chosen: best resolution for X-ray and cryo-EM, best coverage for NMR,
ties broken alphabetically. A multi-chain entry contributes one chain, so every comparison is one
chain against one chain (notebook 03 uses the other copies in the same entry as the tightest reference).

If fewer than 15 proteins remain, relax **one** rule at a time, in this order, and report which:
`MAX_EM` 4.0 → 4.5, `MIN_COVERAGE` 0.8 → 0.7, `LENGTH` upper 300 → 400.

In [15]:
MAX_XRAY, MAX_EM = 2.5, 4.0  # Å
LENGTH = (50, 300)  # mature chain, residues
MIN_COVERAGE = 0.8  # fraction of the mature chain modelled in the chain
REF_DIR = os.path.join(DATA_DIR, "reference")

ref = ds.download_reference_files(REF_DIR)
print("SIFTS version:", ds.sifts_version(ref["uniprot_segments_observed.csv.gz"]))

segments = ds.load_segments(ref["uniprot_segments_observed.csv.gz"])
chains = ds.chain_table(
    segments,
    ds.load_methods(ref["pdb_entry_type.txt"]),
    ds.load_resolution(ref["resolu.idx"]),
    MAX_XRAY,
    MAX_EM,
)

# How many proteins have structures of each method (within the quality limits)?  NMR is the scarcest.
print(chains.groupby("method")["uniprot"].nunique().to_string())
candidates = ds.proteins_with(chains, ("NMR", "Cryo-EM"))
print(
    f"NMR and cryo-EM: {len(candidates)} proteins | "
    f"NMR, cryo-EM and X-ray: {len(ds.proteins_with(chains, ('NMR', 'Cryo-EM', 'X-ray')))}"
)

  [skip] uniprot_segments_observed.csv.gz already present (force=True to refresh)
  [skip] pdb_entry_type.txt already present (force=True to refresh)
  [skip] resolu.idx already present (force=True to refresh)
SIFTS version: 2026/09/27 - 11:11
method
Cryo-EM    24250
NMR         6910
X-ray      42359
NMR and cryo-EM: 1055 proteins | NMR, cryo-EM and X-ray: 684

### Protein facts, coverage and filters

UniProt gives the mature chain of each candidate (e.g. barnase: residues 48–157 of 157).
Coverage is measured against it. The counts table below is the dataset table of the thesis.

In [16]:
facts = ds.fetch_uniprot_facts(
    candidates, cache_path=os.path.join(REF_DIR, "uniprot_facts.csv")
)
cov = ds.add_coverage(chains[chains["uniprot"].isin(candidates)], segments, facts)
both = lambda d: d[d["uniprot"].isin(ds.proteins_with(d))]

kept, counts = ds.filter_with_counts(
    cov,
    [
        ("single mature chain (no polyprotein)", lambda d: d[d["n_chains"] <= 1]),
        (
            f"mature length {LENGTH[0]}-{LENGTH[1]}",
            lambda d: d[d["mature_length"].between(*LENGTH)],
        ),
        (
            f"NMR and cryo-EM chains covering >= {MIN_COVERAGE:.0%}",
            lambda d: both(d[d["coverage"] >= MIN_COVERAGE]),
        ),
    ],
    start_label="NMR and cryo-EM, found in UniProt",
)

survivors = sorted(kept["uniprot"].unique())
af2 = {acc: ds.has_alphafold_model(acc) for acc in survivors}
kept, more = ds.filter_with_counts(
    kept, [("AlphaFold DB model exists", lambda d: d[d["uniprot"].map(af2)])]
)
counts = pd.concat([counts, more.iloc[1:]], ignore_index=True)
os.makedirs("results", exist_ok=True)
counts.to_csv("results/dataset_selection_counts.csv", index=False)
display(counts)

                                     step  proteins
0       NMR and cryo-EM, found in UniProt      1055
1    single mature chain (no polyprotein)       938
2                    mature length 50-300       392
3  NMR and cryo-EM chains covering >= 80%       161
4               AlphaFold DB model exists       151

### One chain per method → `proteins.csv`

In [17]:
representatives = ds.pick_representatives(kept)
manifest = ds.write_manifest(representatives, facts, path="proteins.csv")
print(f"proteins.csv written: {len(manifest)} proteins")
display(manifest)

proteins = pd.read_csv("proteins.csv", dtype=str, keep_default_na=False)

proteins.csv written: 151 proteins

,protein_name,uniprot_id,organism,mature_start,mature_end,pdb_xray,chain_xray,pdb_nmr,chain_nmr,pdb_cryoem,chain_cryoem,cov_xray,cov_nmr,cov_cryoem,res_xray,res_cryoem,notes
0,Type IV pilin PilE1,A0A0B7GU52,Streptococcus sanguinis,19,157,,,6I2O,A,8PFB,C,,0.813,0.942,,3.67,
1,Toxin co-regulated pilus biosynthesis protein ...,A0AAI7ZGD2,Xanthomonas citri pv. citri (strain 306),22,139,,,2L4W,A,6GYB,A,,0.983,0.941,,3.28,
2,ATP synthase epsilon chain (B1MLW3),B1MLW3,Mycobacteroides abscessus (strain ATCC 19977 /...,1,121,,,7VIL,A,9VKR,H,,0.992,1.000,,2.79,
3,Type II secretion system core protein G,E0SM38,Dickeya dadantii (strain 3937) (Erwinia chrysa...,8,153,,,29JD,A,11ME,B,,0.836,0.904,,3.60,
4,"Acyl carrier protein, mitochondrial",O14561,Homo sapiens (Human),69,156,6ODD,A,2DNW,A,7OF0,w,0.966,0.977,0.898,2.0,2.20,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,Dynein axonemal light chain 1,Q9XHH2,Chlamydomonas reinhardtii (Chlamydomonas smithii),1,198,5YXM,A,1DS9,A,8GLV,AA,0.98,1.000,0.985,1.545,3.10,
147,Cofilin-2 (Q9Y281),Q9Y281,Homo sapiens (Human),2,166,,,7M0G,A,9Y9P,a,,1.000,1.000,,2.06,
148,Ribosome maturation protein SBDS,Q9Y3A5,Homo sapiens (Human),2,250,,,2KDO,A,5AN9,J,,1.000,1.000,,3.30,
149,Peptidyl-prolyl cis-trans isomerase-like 1,Q9Y3C6,Homo sapiens (Human),1,166,2X7K,A,1XWN,A,9S2E,S,0.988,1.000,0.958,1.15,2.40,
150,Phage protein,V9H5N5,Simonsiella muelleri ATCC 29453,1,130,,,8JB9,A,8HJ4,C,,1.000,1.000,,3.10,

---
## Download experimental structures

Downloads the X-ray, NMR and cryo-EM entries listed in `proteins.csv` into `data/experimental/`.
Methods without an entry are skipped; files that already exist are not re-downloaded.

In [18]:
proteins = pd.read_csv("proteins.csv", dtype=str, keep_default_na=False)

download_log = []

for _, row in proteins.iterrows():
    name = row["protein_name"]
    uid = row["uniprot_id"]

    for method, col in [
        ("X-ray", "pdb_xray"),
        ("NMR", "pdb_nmr"),
        ("Cryo-EM", "pdb_cryoem"),
    ]:
        pdb_id = row.get(col)
        if pd.isna(pdb_id) or not str(pdb_id).strip():
            continue  # no structure for this method

        pdb_id = str(pdb_id).strip().upper()
        dest = os.path.join(EXP_DIR, f"{pdb_id}.cif")

        if os.path.exists(dest):
            continue  # already on disk

        print(f"  [{method:8s}] {name} — downloading {pdb_id}")
        try:
            download_rcsb(pdb_id, EXP_DIR)
            download_log.append(
                {"protein": name, "method": method, "pdb_id": pdb_id, "status": "ok"}
            )
        except Exception as exc:
            print(f"  [ERROR] {pdb_id}: {exc}")
            download_log.append(
                {
                    "protein": name,
                    "method": method,
                    "pdb_id": pdb_id,
                    "status": str(exc),
                }
            )

if download_log:
    print(f"\nDownload complete — {len(download_log)} file(s) downloaded or attempted.")
    display(pd.DataFrame(download_log))
else:
    print("All experimental CIF files already present — nothing to download.")

All experimental CIF files already present — nothing to download.

---
## AlphaFold2 predictions

Downloads AF2 predictions from the AlphaFold Protein Structure Database
(https://alphafold.ebi.ac.uk/) for **every protein currently in `proteins.csv`**.
The API always returns the latest model version. Existing files are skipped.

In [19]:
proteins = pd.read_csv("proteins.csv", dtype=str, keep_default_na=False)
print(f"Downloading AF2 for {len(proteins)} proteins...")

for _, row in proteins.iterrows():
    print(f"  {row['protein_name']} ({row['uniprot_id']})")
    try:
        download_alphafold2(row["uniprot_id"], AF2_DIR)
    except Exception as exc:
        print(f"    [ERROR] {exc}")

Downloading AF2 for 151 proteins...
  Type IV pilin PilE1 (A0A0B7GU52)
  [skip] AF2_A0A0B7GU52.cif already exists
  Toxin co-regulated pilus biosynthesis protein Q C-terminal domain-containing protein (A0AAI7ZGD2)
  [skip] AF2_A0AAI7ZGD2.cif already exists
  ATP synthase epsilon chain (B1MLW3) (B1MLW3)
  [skip] AF2_B1MLW3.cif already exists
  Type II secretion system core protein G (E0SM38)
  [skip] AF2_E0SM38.cif already exists
  Acyl carrier protein, mitochondrial (O14561)
  [skip] AF2_O14561.cif already exists
  C-X-C motif chemokine 11 (O14625)
  [skip] AF2_O14625.cif already exists
  Ubiquitin/ISG15-conjugating enzyme E2 L6 (O14933)
  [skip] AF2_O14933.cif already exists
  Baculoviral IAP repeat-containing protein 5 (O15392)
  [skip] AF2_O15392.cif already exists
  NADH dehydrogenase [ubiquinone] 1 alpha subcomplex subunit 2 (O43678)
  [skip] AF2_O43678.cif already exists
  Dynein light chain Tctex1 (O64980)
  [skip] AF2_O64980.cif already exists
  Gamma-aminobutyric acid receptor-associated protein (O95166)
  [skip] AF2_O95166.cif already exists
  Anterior gradient protein 2 homolog (O95994)
  [skip] AF2_O95994.cif already exists
  Cytochrome c (P00004)
  [skip] AF2_P00004.cif already exists
  Plastocyanin, chloroplastic (P00289)
  [skip] AF2_P00289.cif already exists
  Lysozyme C (P00698) (P00698)
  [skip] AF2_P00698.cif already exists
  ATP synthase subunit c (P00845) (P00845)
  [skip] AF2_P00845.cif already exists
  Glycoprotein hormones alpha chain (P01215)
  [skip] AF2_P01215.cif already exists
  Alpha-cobratoxin (P01391)
  [skip] AF2_P01391.cif already exists
  Beta-mammal toxin Cn2 (P01495)
  [skip] AF2_P01495.cif already exists
  Histone H2B (P02283)
  [skip] AF2_P02283.cif already exists
  ATP synthase peripheral stalk subunit F6, mitochondrial (P02721)
  [skip] AF2_P02721.cif already exists
  Transthyretin (P02766)
  [skip] AF2_P02766.cif already exists
  Light-harvesting protein B-870 alpha chain (P02947)
  [skip] AF2_P02947.cif already exists
  Angiogenin (P03950)
  [skip] AF2_P03950.cif already exists
  Type-1 fimbrial protein, A chain (P04128)
  [skip] AF2_P04128.cif already exists
  Histone H2A type 1-B/E (P04908)
  [skip] AF2_P04908.cif already exists
  Rod cGMP 3',5'-cyclic phosphodiesterase subunit gamma (P04972)
  [skip] AF2_P04972.cif already exists
  Insulin-like growth factor 1 (P05019)
  [skip] AF2_P05019.cif already exists
  Interleukin-6 (P05231)
  [skip] AF2_P05231.cif already exists
  Protein S100-A9 (P06702)
  [skip] AF2_P06702.cif already exists
  Histone H2B type 1-J (P06899)
  [skip] AF2_P06899.cif already exists
  Profilin-1 (P07737)
  [skip] AF2_P07737.cif already exists
  DELTA-stichotoxin-She4b (P07845)
  [skip] AF2_P07845.cif already exists
  Protein FimF (P08189)
  [skip] AF2_P08189.cif already exists
  Ferredoxin-1 (P0A3C9)
  [skip] AF2_P0A3C9.cif already exists
  Lactococcin-A immunity protein (P0A3M7)
  [skip] AF2_P0A3M7.cif already exists
  Acyl carrier protein (P0A6A8)
  [skip] AF2_P0A6A8.cif already exists
  ATP synthase epsilon chain (P0A6E6) (P0A6E6)
  [skip] AF2_P0A6E6.cif already exists
  Peptide deformylase (P0A6K3)
  [skip] AF2_P0A6K3.cif already exists
  Transcription antitermination protein NusB (P0A780)
  [skip] AF2_P0A780.cif already exists
  Ribonuclease P protein component (P0A7Y8)
  [skip] AF2_P0A7Y8.cif already exists
  Ribosome maturation factor RimP (P0A8A8)
  [skip] AF2_P0A8A8.cif already exists
  Outer membrane protein assembly factor BamE (P0A937)
  [skip] AF2_P0A937.cif already exists
  Phosphocarrier protein HPr (P0AA04)
  [skip] AF2_P0AA04.cif already exists
  Thioredoxin 1 (P0AA25)
  [skip] AF2_P0AA25.cif already exists
  Soluble cytochrome b562 (P0ABE7)
  [skip] AF2_P0ABE7.cif already exists
  DNA damage-inducible protein I (P0ABR1)
  [skip] AF2_P0ABR1.cif already exists
  DNA-binding transcriptional dual regulator CRP (P0ACJ8)
  [skip] AF2_P0ACJ8.cif already exists
  Ribosome-associated inhibitor A (P0AD49)
  [skip] AF2_P0AD49.cif already exists
  Cell division activator CedA (P0AE60)
  [skip] AF2_P0AE60.cif already exists
  Peptidyl-prolyl cis-trans isomerase A (P0AFL3)
  [skip] AF2_P0AFL3.cif already exists
  Protein rof (P0AFW8)
  [skip] AF2_P0AFW8.cif already exists
  Ribosome hibernation promoting factor (P0AFX0)
  [skip] AF2_P0AFX0.cif already exists
  Tau-theraphotoxin-Hs1a (P0CH43)
  [skip] AF2_P0CH43.cif already exists
  Mambalgin-1 (P0DKR6)
  [skip] AF2_P0DKR6.cif already exists
  Calmodulin-1 (P0DP23) (P0DP23)
  [skip] AF2_P0DP23.cif already exists
  Calmodulin-1 (P0DP29) (P0DP29)
  [skip] AF2_P0DP29.cif already exists
  ADP-ribosylation factor 1 (P11076) (P11076)
  [skip] AF2_P11076.cif already exists
  Oxygen-evolving enhancer protein 3, chloroplastic (P12301)
  [skip] AF2_P12301.cif already exists
  Photosystem I reaction center subunit IV (P12975)
  [skip] AF2_P12975.cif already exists
  Intrinsic membrane protein PufX (P13402)
  [skip] AF2_P13402.cif already exists
  C-C motif chemokine 2 (P13500)
  [skip] AF2_P13500.cif already exists
  CD59 glycoprotein (P13987)
  [skip] AF2_P13987.cif already exists
  Large ribosomal subunit protein eL30 (P14120)
  [skip] AF2_P14120.cif already exists
  Thioredoxin (P14949)
  [skip] AF2_P14949.cif already exists
  Major pollen allergen Bet v 1-A (P15494)
  [skip] AF2_P15494.cif already exists
  Alpha-insect toxin LqhaIT (P17728)
  [skip] AF2_P17728.cif already exists
  DNA-directed RNA polymerases I, II, and III subunit RPABC3 (P20436) (P20436)
  [skip] AF2_P20436.cif already exists
  Cofilin-2 (P21566) (P21566)
  [skip] AF2_P21566.cif already exists
  Non-selective voltage-gated ion channel VDAC1 (P21796)
  [skip] AF2_P21796.cif already exists
  Cofilin-1 (P23528)
  [skip] AF2_P23528.cif already exists
  Proteasome subunit alpha (P25156)
  [skip] AF2_P25156.cif already exists
  Pre-mRNA-splicing factor BUD31 (P25337)
  [skip] AF2_P25337.cif already exists
  Aquaporin-1 (P29972)
  [skip] AF2_P29972.cif already exists
  Large ribosomal subunit protein uL11 (P30050) (P30050)
  [skip] AF2_P30050.cif already exists
  Chaperone protein FimC (P31697)
  [skip] AF2_P31697.cif already exists
  Cytochrome c oxidase subunit 13, mitochondrial (P32799)
  [skip] AF2_P32799.cif already exists
  Eukaryotic translation initiation factor eIF-1 (P32911)
  [skip] AF2_P32911.cif already exists
  Interleukin-13 (P35225)
  [skip] AF2_P35225.cif already exists
  Leptin (P41159)
  [skip] AF2_P41159.cif already exists
  Eukaryotic translation initiation factor 1 (P41567)
  [skip] AF2_P41567.cif already exists
  SPI-1 type 3 secretion system needle filament protein (P41784)
  [skip] AF2_P41784.cif already exists
  Eukaryotic translation initiation factor 1A, X-chromosomal (P47813)
  [skip] AF2_P47813.cif already exists
  Beta-diguetoxin-Dc1a (P49126)
  [skip] AF2_P49126.cif already exists
  DNA-directed RNA polymerases I, II, and III subunit RPABC3 (P52434) (P52434)
  [skip] AF2_P52434.cif already exists
  Alpha-like toxin Lqh3 (P56678)
  [skip] AF2_P56678.cif already exists
  Large ribosomal subunit protein uL16 (P60489)
  [skip] AF2_P60489.cif already exists
  Interleukin-2 (P60568)
  [skip] AF2_P60568.cif already exists
  Alpha-bungarotoxin (P60615)
  [skip] AF2_P60615.cif already exists
  Aquaporin Z (P60844)
  [skip] AF2_P60844.cif already exists
  Cell division control protein 42 homolog (P60953)
  [skip] AF2_P60953.cif already exists
  Ubiquitin-conjugating enzyme E2 D3 (P61077)
  [skip] AF2_P61077.cif already exists
  Lysozyme C (P61626) (P61626)
  [skip] AF2_P61626.cif already exists
  Ubiquitin-fold modifier 1 (P61960)
  [skip] AF2_P61960.cif already exists
  Histone H4 (P62799)
  [skip] AF2_P62799.cif already exists
  GTP-binding nuclear protein Ran (P62826)
  [skip] AF2_P62826.cif already exists
  Ubiquitin-conjugating enzyme E2 D2 (P62837)
  [skip] AF2_P62837.cif already exists
  Peptidyl-prolyl cis-trans isomerase FKBP1A (P62942)
  [skip] AF2_P62942.cif already exists
  Ras-related C3 botulinum toxin substrate 1 (P63000)
  [skip] AF2_P63000.cif already exists
  Small ubiquitin-related modifier 1 (P63165)
  [skip] AF2_P63165.cif already exists
  S-phase kinase-associated protein 1 (P63208)
  [skip] AF2_P63208.cif already exists
  SUMO-conjugating enzyme UBC9 (P63279)
  [skip] AF2_P63279.cif already exists
  Ubiquitin-conjugating enzyme E2 L3 (P68036)
  [skip] AF2_P68036.cif already exists
  ATP synthase subunit c (P68699) (P68699)
  [skip] AF2_P68699.cif already exists
  Hemoglobin subunit beta (P68871)
  [skip] AF2_P68871.cif already exists
  Large ribosomal subunit protein bL25 (P68919)
  [skip] AF2_P68919.cif already exists
  Translation initiation factor IF-1 (P69222)
  [skip] AF2_P69222.cif already exists
  Capsid protein G8P (P69541)
  [skip] AF2_P69541.cif already exists
  Hemoglobin subunit alpha (P69905)
  [skip] AF2_P69905.cif already exists
  C-C motif chemokine 7 (P80098)
  [skip] AF2_P80098.cif already exists
  Thioredoxin-like protein 4A (P83876)
  [skip] AF2_P83876.cif already exists
  Histone H2A (P84051)
  [skip] AF2_P84051.cif already exists
  ADP-ribosylation factor 1 (P84077) (P84077)
  [skip] AF2_P84077.cif already exists
  ATP synthase epsilon chain (P9WPV1) (P9WPV1)
  [skip] AF2_P9WPV1.cif already exists
  Telomere replication protein EST3 (Q03096)
  [skip] AF2_Q03096.cif already exists
  Pre-mRNA-splicing factor RDS3 (Q06835)
  [skip] AF2_Q06835.cif already exists
  Mitotic spindle assembly checkpoint protein MAD2A (Q13257)
  [skip] AF2_Q13257.cif already exists
  Interleukin-18 (Q14116)
  [skip] AF2_Q14116.cif already exists
  Elongin-C (Q15369)
  [skip] AF2_Q15369.cif already exists
  Elongin-B (Q15370)
  [skip] AF2_Q15370.cif already exists
  Ubiquitin-like protein NEDD8 (Q15843)
  [skip] AF2_Q15843.cif already exists
  Ribosome-binding factor A (Q2G2Q4)
  [skip] AF2_Q2G2Q4.cif already exists
  Light-harvesting protein B-870 beta chain (Q2RQ23)
  [skip] AF2_Q2RQ23.cif already exists
  Regulatory protein Cgi121 (Q57646)
  [skip] AF2_Q57646.cif already exists
  Large ribosomal subunit protein uL11 (Q5SLP6) (Q5SLP6)
  [skip] AF2_Q5SLP6.cif already exists
  Small ribosomal subunit protein bS6 (Q5SLP8)
  [skip] AF2_Q5SLP8.cif already exists
  H/ACA ribonucleoprotein complex subunit NOP10 (Q6Q547)
  [skip] AF2_Q6Q547.cif already exists
  General transcription factor IIH subunit 5 (Q6ZYL4)
  [skip] AF2_Q6ZYL4.cif already exists
  Geopilin domain 1 protein (Q74D23)
  [skip] AF2_Q74D23.cif already exists
  Sigma factor-binding protein Crl (Q7CR52)
  [skip] AF2_Q7CR52.cif already exists
  Tll0220 protein (Q8DMA1)
  [skip] AF2_Q8DMA1.cif already exists
  Far1 (Q8GNY5)
  [skip] AF2_Q8GNY5.cif already exists
  RNA polymerase inhibitor p7 (Q8LTJ5)
  [skip] AF2_Q8LTJ5.cif already exists
  SsrA-binding protein (Q8RR57)
  [skip] AF2_Q8RR57.cif already exists
  Large ribosomal subunit protein eL33 (Q8TZV6)
  [skip] AF2_Q8TZV6.cif already exists
  Large ribosomal subunit protein eL8 (Q8U160)
  [skip] AF2_Q8U160.cif already exists
  Translation initiation factor 2 subunit beta (Q97W59)
  [skip] AF2_Q97W59.cif already exists
  Small ribosomal subunit protein eS8 (Q980W3)
  [skip] AF2_Q980W3.cif already exists
  Calcineurin B homologous protein 1 (Q99653)
  [skip] AF2_Q99653.cif already exists
  C-C motif chemokine 19 (Q99731)
  [skip] AF2_Q99731.cif already exists
  Coat protein (Q9AZ42)
  [skip] AF2_Q9AZ42.cif already exists
  Ubiquitin-like protein 5 (Q9BZL1)
  [skip] AF2_Q9BZL1.cif already exists
  MbtH-like domain-containing protein (Q9I169)
  [skip] AF2_Q9I169.cif already exists
  Dynein light chain roadblock-type 1 (Q9NP97)
  [skip] AF2_Q9NP97.cif already exists
  Anaphase-promoting complex subunit 11 (Q9NYG5)
  [skip] AF2_Q9NYG5.cif already exists
  Apoptosis-associated speck-like protein containing a CARD (Q9ULZ3)
  [skip] AF2_Q9ULZ3.cif already exists
  Dynein axonemal light chain 1 (Q9XHH2)
  [skip] AF2_Q9XHH2.cif already exists
  Cofilin-2 (Q9Y281) (Q9Y281)
  [skip] AF2_Q9Y281.cif already exists
  Ribosome maturation protein SBDS (Q9Y3A5)
  [skip] AF2_Q9Y3A5.cif already exists
  Peptidyl-prolyl cis-trans isomerase-like 1 (Q9Y3C6)
  [skip] AF2_Q9Y3C6.cif already exists
  Phage protein (V9H5N5)
  [skip] AF2_V9H5N5.cif already exists

---
## OpenFold3 predictions (with MSA)

**Why an MSA.** OpenFold3, like AlphaFold2, infers a fold mainly from evolution: the multiple
sequence alignment (MSA) of homologous sequences. With the query sequence alone (an MSA of depth 1)
the predictions of a test on the proteins of the set had a median pLDDT of 29 and none reached 70 —
not usable predictions — so every protein is predicted with an MSA.

**What is run, per protein:**
1. the UniProt canonical sequence — the sequence the AlphaFold DB model was predicted from;
2. its MSA from the NVIDIA MSA Search NIM (ColabFold MMseqs2 search of UniRef30 and the ColabFold
   environmental database), cached in `data/msas/<UniProt>/`;
3. OpenFold3 on NVIDIA NIM with that MSA and 5 diffusion samples. The top-ranked sample (highest
   `confidence_score`) becomes `data/openfold3/OF3_<UniProt>.cif`; all samples go to
   `data/openfold3/samples/`; scores and MSA depth to `OF3_<UniProt>_provenance.json`.

AF2 and OF3 models both cover the whole UniProt sequence.

Model: OpenFold3-preview (OpenFold Consortium), https://github.com/aqlaboratory/openfold-3 —
an open reproduction of AlphaFold3 (Abramson et al., *Nature* 2024, doi:10.1038/s41586-024-07487-w).
**Requires `NIM_API_KEY`** in `.env`. Existing MSAs and models are never requested again.

In [20]:
# 1. Sequences and checks. No NIM request is sent in this cell.
proteins = pd.read_csv("proteins.csv", dtype=str, keep_default_na=False)
STANDARD = set("ACDEFGHIKLMNPQRSTVWY")
FLAGS = ["standard letters", "AF2 = UniProt sequence"]

sequences, checks = {}, []
for _, row in proteins.iterrows():
    uid = row["uniprot_id"]
    check = {"uniprot_id": uid}
    try:
        seq = sequences[uid] = fetch_uniprot_sequence(uid)
        af2 = load_structure(os.path.join(AF2_DIR, f"AF2_{uid}.cif"))
        _, af2_seq = get_ca_coords_and_seq(af2, 0, "A")
        check.update(
            {
                "length": len(seq),
                "standard letters": set(seq) <= STANDARD,
                "AF2 = UniProt sequence": af2_seq == seq,
            }
        )
    except Exception as exc:  # e.g. a missing AF2 file or a UniProt time-out
        check["error"] = str(exc)
    checks.append(check)

checks = pd.DataFrame(checks).reindex(columns=["uniprot_id", "length", *FLAGS, "error"])
passed = checks[FLAGS].eq(True).all(axis=1)
print(f"{passed.sum()} of {len(checks)} proteins pass every check")
print(f"{checks['length'].sum():.0f} residues in total")
print(checks[FLAGS].eq(True).sum().to_string())  # proteins passing each check
display(checks[~passed])  # proteins failing a check, with the error if any

151 of 151 proteins pass every check
20163 residues in total
standard letters          151
AF2 = UniProt sequence    151

Empty DataFrame
Columns: [uniprot_id, length, standard letters, AF2 = UniProt sequence, error]
Index: []

### Pilot: three proteins first

Decision rule, written before running: **go** if, for every pilot protein, the OF3 pLDDT is ≥ 70
and at most 10 points below AF2's. Otherwise look at that protein's MSA depth
and stop before the batch.

In [21]:
# 2. Pilot: thioredoxin (P0AA25), the protein with the most residues before its mature chain
#    (signal peptide / propeptide) and the longest protein.
MSA_DIR = os.path.join(DATA_DIR, "msas")
with_prepeptide = proteins.loc[
    proteins["mature_start"].astype(int).idxmax(), "uniprot_id"
]
longest = checks.loc[checks["length"].idxmax(), "uniprot_id"]
PILOT = list(dict.fromkeys(["P0AA25", with_prepeptide, longest]))

for uid in PILOT:
    if uid not in sequences:  # its UniProt request failed in cell 1
        sequences[uid] = fetch_uniprot_sequence(uid)
    msa = fetch_msa(uid, sequences[uid], save_dir=MSA_DIR)
    predict_openfold3(uid, sequences[uid], OF3_DIR, msa=msa)

  [skip] MSA for P0AA25 already exists
  [skip] OF3_P0AA25.cif already exists
  [skip] MSA for P12301 already exists
  [skip] OF3_P12301.cif already exists
  [skip] MSA for P21796 already exists
  [skip] OF3_P21796.cif already exists

In [22]:
def of3_report(uids) -> pd.DataFrame:
    """
    Per protein: whether the OF3 model has the UniProt sequence; MSA depth;
    mean pLDDT of OF3 and AF2.
    """

    def plddt(path):
        if not os.path.exists(path):
            return None
        return extract_metadata(path).plddt_mean

    rows = []
    for uid in uids:
        of3 = os.path.join(OF3_DIR, f"OF3_{uid}.cif")
        if not os.path.exists(of3):
            continue
        with open(of3.replace(".cif", "_provenance.json")) as f:
            prov = json.load(f)
        _, of3_seq = get_ca_coords_and_seq(load_structure(of3), 0, "A")
        rows.append(
            {
                "uniprot_id": uid,
                "OF3 = UniProt sequence": of3_seq == sequences.get(uid),
                "MSA depth": " + ".join(
                    str(n) for n in prov["msa_n_sequences"].values()
                ),
                "confidence": prov["sample_scores"][prov["selected_sample"]].get(
                    "confidence_score"
                ),
                "pLDDT OF3": plddt(of3),
                "pLDDT AF2": plddt(os.path.join(AF2_DIR, f"AF2_{uid}.cif")),
            }
        )
    return pd.DataFrame(rows).round(1)


of3_report(PILOT)

,uniprot_id,OF3 = UniProt sequence,MSA depth,confidence,pLDDT OF3,pLDDT AF2
0,P0AA25,True,101 + 101,0.7,86.9,95.2
1,P12301,True,103 + 101,0.2,70.6,71.6
2,P21796,True,101 + 101,0.5,81.3,93.1

### All proteins (only after the pilot passes)

Re-running the cell continues where it stopped: MSAs and models already on disk are skipped.

In [23]:
# 3. Batch
failed = {}
for i, uid in enumerate(proteins["uniprot_id"], start=1):
    print(f"[{i}/{len(proteins)}] {uid}")
    try:
        if uid not in sequences:  # its UniProt request failed in cell 1
            sequences[uid] = fetch_uniprot_sequence(uid)
        msa = fetch_msa(uid, sequences[uid], save_dir=MSA_DIR)
        predict_openfold3(uid, sequences[uid], OF3_DIR, msa=msa)
    except Exception as exc:
        failed[uid] = str(exc)
        print(f"  [ERROR] {exc}")

print(f"\n{len(proteins) - len(failed)} of {len(proteins)} proteins have an OF3 model")
display(pd.Series(failed, name="error", dtype=str))

[1/151] A0A0B7GU52
  [skip] MSA for A0A0B7GU52 already exists
  [skip] OF3_A0A0B7GU52.cif already exists
[2/151] A0AAI7ZGD2
  [skip] MSA for A0AAI7ZGD2 already exists
  [skip] OF3_A0AAI7ZGD2.cif already exists
[3/151] B1MLW3
  [skip] MSA for B1MLW3 already exists
  [skip] OF3_B1MLW3.cif already exists
[4/151] E0SM38
  [skip] MSA for E0SM38 already exists
  [skip] OF3_E0SM38.cif already exists
[5/151] O14561
  [skip] MSA for O14561 already exists
  [skip] OF3_O14561.cif already exists
[6/151] O14625
  [skip] MSA for O14625 already exists
  [skip] OF3_O14625.cif already exists
[7/151] O14933
  [skip] MSA for O14933 already exists
  [skip] OF3_O14933.cif already exists
[8/151] O15392
  [skip] MSA for O15392 already exists
  [skip] OF3_O15392.cif already exists
[9/151] O43678
  [skip] MSA for O43678 already exists
  [skip] OF3_O43678.cif already exists
[10/151] O64980
  [skip] MSA for O64980 already exists
  [skip] OF3_O64980.cif already exists
[11/151] O95166
  [skip] MSA for O95166 already exists
  [skip] OF3_O95166.cif already exists
[12/151] O95994
  [skip] MSA for O95994 already exists
  [skip] OF3_O95994.cif already exists
[13/151] P00004
  [skip] MSA for P00004 already exists
  [skip] OF3_P00004.cif already exists
[14/151] P00289
  [skip] MSA for P00289 already exists
  [skip] OF3_P00289.cif already exists
[15/151] P00698
  [skip] MSA for P00698 already exists
  [skip] OF3_P00698.cif already exists
[16/151] P00845
  [skip] MSA for P00845 already exists
  [skip] OF3_P00845.cif already exists
[17/151] P01215
  [skip] MSA for P01215 already exists
  [skip] OF3_P01215.cif already exists
[18/151] P01391
  [skip] MSA for P01391 already exists
  [skip] OF3_P01391.cif already exists
[19/151] P01495
  [skip] MSA for P01495 already exists
  [skip] OF3_P01495.cif already exists
[20/151] P02283
  [skip] MSA for P02283 already exists
  [skip] OF3_P02283.cif already exists
[21/151] P02721
  [skip] MSA for P02721 already exists
  [skip] OF3_P02721.cif already exists
[22/151] P02766
  [skip] MSA for P02766 already exists
  [skip] OF3_P02766.cif already exists
[23/151] P02947
  [skip] MSA for P02947 already exists
  [skip] OF3_P02947.cif already exists
[24/151] P03950
  [skip] MSA for P03950 already exists
  [skip] OF3_P03950.cif already exists
[25/151] P04128
  [skip] MSA for P04128 already exists
  [skip] OF3_P04128.cif already exists
[26/151] P04908
  [skip] MSA for P04908 already exists
  [skip] OF3_P04908.cif already exists
[27/151] P04972
  [skip] MSA for P04972 already exists
  [skip] OF3_P04972.cif already exists
[28/151] P05019
  [skip] MSA for P05019 already exists
  [skip] OF3_P05019.cif already exists
[29/151] P05231
  [skip] MSA for P05231 already exists
  [skip] OF3_P05231.cif already exists
[30/151] P06702
  [skip] MSA for P06702 already exists
  [skip] OF3_P06702.cif already exists
[31/151] P06899
  [skip] MSA for P06899 already exists
  [skip] OF3_P06899.cif already exists
[32/151] P07737
  [skip] MSA for P07737 already exists
  [skip] OF3_P07737.cif already exists
[33/151] P07845
  [skip] MSA for P07845 already exists
  [skip] OF3_P07845.cif already exists
[34/151] P08189
  [skip] MSA for P08189 already exists
  [skip] OF3_P08189.cif already exists
[35/151] P0A3C9
  [skip] MSA for P0A3C9 already exists
  [skip] OF3_P0A3C9.cif already exists
[36/151] P0A3M7
  [skip] MSA for P0A3M7 already exists
  [skip] OF3_P0A3M7.cif already exists
[37/151] P0A6A8
  [skip] MSA for P0A6A8 already exists
  [skip] OF3_P0A6A8.cif already exists
[38/151] P0A6E6
  [skip] MSA for P0A6E6 already exists
  [skip] OF3_P0A6E6.cif already exists
[39/151] P0A6K3
  [skip] MSA for P0A6K3 already exists
  [skip] OF3_P0A6K3.cif already exists
[40/151] P0A780
  [skip] MSA for P0A780 already exists
  [skip] OF3_P0A780.cif already exists
[41/151] P0A7Y8
  [skip] MSA for P0A7Y8 already exists
  [skip] OF3_P0A7Y8.cif already exists
[42/151] P0A8A8
  [skip] MSA for P0A8A8 already exists
  [skip] OF3_P0A8A8.cif already exists
[43/151] P0A937
  [skip] MSA for P0A937 already exists
  [skip] OF3_P0A937.cif already exists
[44/151] P0AA04
  [skip] MSA for P0AA04 already exists
  [skip] OF3_P0AA04.cif already exists
[45/151] P0AA25
  [skip] MSA for P0AA25 already exists
  [skip] OF3_P0AA25.cif already exists
[46/151] P0ABE7
  [skip] MSA for P0ABE7 already exists
  [skip] OF3_P0ABE7.cif already exists
[47/151] P0ABR1
  [skip] MSA for P0ABR1 already exists
  [skip] OF3_P0ABR1.cif already exists
[48/151] P0ACJ8
  [skip] MSA for P0ACJ8 already exists
  [skip] OF3_P0ACJ8.cif already exists
[49/151] P0AD49
  [skip] MSA for P0AD49 already exists
  [skip] OF3_P0AD49.cif already exists
[50/151] P0AE60
  [skip] MSA for P0AE60 already exists
  [skip] OF3_P0AE60.cif already exists
[51/151] P0AFL3
  [skip] MSA for P0AFL3 already exists
  [skip] OF3_P0AFL3.cif already exists
[52/151] P0AFW8
  [skip] MSA for P0AFW8 already exists
  [skip] OF3_P0AFW8.cif already exists
[53/151] P0AFX0
  [skip] MSA for P0AFX0 already exists
  [skip] OF3_P0AFX0.cif already exists
[54/151] P0CH43
  [skip] MSA for P0CH43 already exists
  [skip] OF3_P0CH43.cif already exists
[55/151] P0DKR6
  [skip] MSA for P0DKR6 already exists
  [skip] OF3_P0DKR6.cif already exists
[56/151] P0DP23
  [skip] MSA for P0DP23 already exists
  [skip] OF3_P0DP23.cif already exists
[57/151] P0DP29
  [skip] MSA for P0DP29 already exists
  [skip] OF3_P0DP29.cif already exists
[58/151] P11076
  [skip] MSA for P11076 already exists
  [skip] OF3_P11076.cif already exists
[59/151] P12301
  [skip] MSA for P12301 already exists
  [skip] OF3_P12301.cif already exists
[60/151] P12975
  [skip] MSA for P12975 already exists
  [skip] OF3_P12975.cif already exists
[61/151] P13402
  [skip] MSA for P13402 already exists
  [skip] OF3_P13402.cif already exists
[62/151] P13500
  [skip] MSA for P13500 already exists
  [skip] OF3_P13500.cif already exists
[63/151] P13987
  [skip] MSA for P13987 already exists
  [skip] OF3_P13987.cif already exists
[64/151] P14120
  [skip] MSA for P14120 already exists
  [skip] OF3_P14120.cif already exists
[65/151] P14949
  [skip] MSA for P14949 already exists
  [skip] OF3_P14949.cif already exists
[66/151] P15494
  [skip] MSA for P15494 already exists
  [skip] OF3_P15494.cif already exists
[67/151] P17728
  [skip] MSA for P17728 already exists
  [skip] OF3_P17728.cif already exists
[68/151] P20436
  [skip] MSA for P20436 already exists
  [skip] OF3_P20436.cif already exists
[69/151] P21566
  [skip] MSA for P21566 already exists
  [skip] OF3_P21566.cif already exists
[70/151] P21796
  [skip] MSA for P21796 already exists
  [skip] OF3_P21796.cif already exists
[71/151] P23528
  [skip] MSA for P23528 already exists
  [skip] OF3_P23528.cif already exists
[72/151] P25156
  [skip] MSA for P25156 already exists
  [skip] OF3_P25156.cif already exists
[73/151] P25337
  [skip] MSA for P25337 already exists
  [skip] OF3_P25337.cif already exists
[74/151] P29972
  [skip] MSA for P29972 already exists
  [skip] OF3_P29972.cif already exists
[75/151] P30050
  [skip] MSA for P30050 already exists
  [skip] OF3_P30050.cif already exists
[76/151] P31697
  [skip] MSA for P31697 already exists
  [skip] OF3_P31697.cif already exists
[77/151] P32799
  [skip] MSA for P32799 already exists
  [skip] OF3_P32799.cif already exists
[78/151] P32911
  [skip] MSA for P32911 already exists
  [skip] OF3_P32911.cif already exists
[79/151] P35225
  [skip] MSA for P35225 already exists
  [skip] OF3_P35225.cif already exists
[80/151] P41159
  [skip] MSA for P41159 already exists
  [skip] OF3_P41159.cif already exists
[81/151] P41567
  [skip] MSA for P41567 already exists
  [skip] OF3_P41567.cif already exists
[82/151] P41784
  [skip] MSA for P41784 already exists
  [skip] OF3_P41784.cif already exists
[83/151] P47813
  [skip] MSA for P47813 already exists
  [skip] OF3_P47813.cif already exists
[84/151] P49126
  [skip] MSA for P49126 already exists
  [skip] OF3_P49126.cif already exists
[85/151] P52434
  [skip] MSA for P52434 already exists
  [skip] OF3_P52434.cif already exists
[86/151] P56678
  [skip] MSA for P56678 already exists
  [skip] OF3_P56678.cif already exists
[87/151] P60489
  [skip] MSA for P60489 already exists
  [skip] OF3_P60489.cif already exists
[88/151] P60568
  [skip] MSA for P60568 already exists
  [skip] OF3_P60568.cif already exists
[89/151] P60615
  [skip] MSA for P60615 already exists
  [skip] OF3_P60615.cif already exists
[90/151] P60844
  [skip] MSA for P60844 already exists
  [skip] OF3_P60844.cif already exists
[91/151] P60953
  [skip] MSA for P60953 already exists
  [skip] OF3_P60953.cif already exists
[92/151] P61077
  [skip] MSA for P61077 already exists
  [skip] OF3_P61077.cif already exists
[93/151] P61626
  [skip] MSA for P61626 already exists
  [skip] OF3_P61626.cif already exists
[94/151] P61960
  [skip] MSA for P61960 already exists
  [skip] OF3_P61960.cif already exists
[95/151] P62799
  [skip] MSA for P62799 already exists
  [skip] OF3_P62799.cif already exists
[96/151] P62826
  [skip] MSA for P62826 already exists
  [skip] OF3_P62826.cif already exists
[97/151] P62837
  [skip] MSA for P62837 already exists
  [skip] OF3_P62837.cif already exists
[98/151] P62942
  [skip] MSA for P62942 already exists
  [skip] OF3_P62942.cif already exists
[99/151] P63000
  [skip] MSA for P63000 already exists
  [skip] OF3_P63000.cif already exists
[100/151] P63165
  [skip] MSA for P63165 already exists
  [skip] OF3_P63165.cif already exists
[101/151] P63208
  [skip] MSA for P63208 already exists
  [skip] OF3_P63208.cif already exists
[102/151] P63279
  [skip] MSA for P63279 already exists
  [skip] OF3_P63279.cif already exists
[103/151] P68036
  [skip] MSA for P68036 already exists
  [skip] OF3_P68036.cif already exists
[104/151] P68699
  [skip] MSA for P68699 already exists
  [skip] OF3_P68699.cif already exists
[105/151] P68871
  [skip] MSA for P68871 already exists
  [skip] OF3_P68871.cif already exists
[106/151] P68919
  [skip] MSA for P68919 already exists
  [skip] OF3_P68919.cif already exists
[107/151] P69222
  [skip] MSA for P69222 already exists
  [skip] OF3_P69222.cif already exists
[108/151] P69541
  [skip] MSA for P69541 already exists
  [skip] OF3_P69541.cif already exists
[109/151] P69905
  [skip] MSA for P69905 already exists
  [skip] OF3_P69905.cif already exists
[110/151] P80098
  [skip] MSA for P80098 already exists
  [skip] OF3_P80098.cif already exists
[111/151] P83876
  [skip] MSA for P83876 already exists
  [skip] OF3_P83876.cif already exists
[112/151] P84051
  [skip] MSA for P84051 already exists
  [skip] OF3_P84051.cif already exists
[113/151] P84077
  [skip] MSA for P84077 already exists
  [skip] OF3_P84077.cif already exists
[114/151] P9WPV1
  [skip] MSA for P9WPV1 already exists
  [skip] OF3_P9WPV1.cif already exists
[115/151] Q03096
  [skip] MSA for Q03096 already exists
  [skip] OF3_Q03096.cif already exists
[116/151] Q06835
  [skip] MSA for Q06835 already exists
  [skip] OF3_Q06835.cif already exists
[117/151] Q13257
  [skip] MSA for Q13257 already exists
  [skip] OF3_Q13257.cif already exists
[118/151] Q14116
  [skip] MSA for Q14116 already exists
  [skip] OF3_Q14116.cif already exists
[119/151] Q15369
  [skip] MSA for Q15369 already exists
  [skip] OF3_Q15369.cif already exists
[120/151] Q15370
  [skip] MSA for Q15370 already exists
  [skip] OF3_Q15370.cif already exists
[121/151] Q15843
  [skip] MSA for Q15843 already exists
  [skip] OF3_Q15843.cif already exists
[122/151] Q2G2Q4
  [skip] MSA for Q2G2Q4 already exists
  [skip] OF3_Q2G2Q4.cif already exists
[123/151] Q2RQ23
  [skip] MSA for Q2RQ23 already exists
  [skip] OF3_Q2RQ23.cif already exists
[124/151] Q57646
  [skip] MSA for Q57646 already exists
  [skip] OF3_Q57646.cif already exists
[125/151] Q5SLP6
  [skip] MSA for Q5SLP6 already exists
  [skip] OF3_Q5SLP6.cif already exists
[126/151] Q5SLP8
  [skip] MSA for Q5SLP8 already exists
  [skip] OF3_Q5SLP8.cif already exists
[127/151] Q6Q547
  [skip] MSA for Q6Q547 already exists
  [skip] OF3_Q6Q547.cif already exists
[128/151] Q6ZYL4
  [skip] MSA for Q6ZYL4 already exists
  [skip] OF3_Q6ZYL4.cif already exists
[129/151] Q74D23
  [skip] MSA for Q74D23 already exists
  [skip] OF3_Q74D23.cif already exists
[130/151] Q7CR52
  [skip] MSA for Q7CR52 already exists
  [skip] OF3_Q7CR52.cif already exists
[131/151] Q8DMA1
  [skip] MSA for Q8DMA1 already exists
  [skip] OF3_Q8DMA1.cif already exists
[132/151] Q8GNY5
  [skip] MSA for Q8GNY5 already exists
  [skip] OF3_Q8GNY5.cif already exists
[133/151] Q8LTJ5
  [skip] MSA for Q8LTJ5 already exists
  [skip] OF3_Q8LTJ5.cif already exists
[134/151] Q8RR57
  [skip] MSA for Q8RR57 already exists
  [skip] OF3_Q8RR57.cif already exists
[135/151] Q8TZV6
  [skip] MSA for Q8TZV6 already exists
  [skip] OF3_Q8TZV6.cif already exists
[136/151] Q8U160
  [skip] MSA for Q8U160 already exists
  [skip] OF3_Q8U160.cif already exists
[137/151] Q97W59
  [skip] MSA for Q97W59 already exists
  [skip] OF3_Q97W59.cif already exists
[138/151] Q980W3
  [skip] MSA for Q980W3 already exists
  [skip] OF3_Q980W3.cif already exists
[139/151] Q99653
  [skip] MSA for Q99653 already exists
  [skip] OF3_Q99653.cif already exists
[140/151] Q99731
  [skip] MSA for Q99731 already exists
  [skip] OF3_Q99731.cif already exists
[141/151] Q9AZ42
  [skip] MSA for Q9AZ42 already exists
  [skip] OF3_Q9AZ42.cif already exists
[142/151] Q9BZL1
  [skip] MSA for Q9BZL1 already exists
  [skip] OF3_Q9BZL1.cif already exists
[143/151] Q9I169
  [skip] MSA for Q9I169 already exists
  [skip] OF3_Q9I169.cif already exists
[144/151] Q9NP97
  [skip] MSA for Q9NP97 already exists
  [skip] OF3_Q9NP97.cif already exists
[145/151] Q9NYG5
  [skip] MSA for Q9NYG5 already exists
  [skip] OF3_Q9NYG5.cif already exists
[146/151] Q9ULZ3
  [skip] MSA for Q9ULZ3 already exists
  [skip] OF3_Q9ULZ3.cif already exists
[147/151] Q9XHH2
  [skip] MSA for Q9XHH2 already exists
  [skip] OF3_Q9XHH2.cif already exists
[148/151] Q9Y281
  [skip] MSA for Q9Y281 already exists
  [skip] OF3_Q9Y281.cif already exists
[149/151] Q9Y3A5
  [skip] MSA for Q9Y3A5 already exists
  [skip] OF3_Q9Y3A5.cif already exists
[150/151] Q9Y3C6
  [skip] MSA for Q9Y3C6 already exists
  [skip] OF3_Q9Y3C6.cif already exists
[151/151] V9H5N5
  [skip] MSA for V9H5N5 already exists
  [skip] OF3_V9H5N5.cif already exists

151 of 151 proteins have an OF3 model

Series([], Name: error, dtype: str)

In [24]:
# 4. Are the predictions valid? pLDDT, OF3 vs AF2
report = of3_report(proteins["uniprot_id"])
display(report[["pLDDT OF3", "pLDDT AF2"]].describe().round(1))
print(f"OF3 pLDDT >= 70: {(report['pLDDT OF3'] >= 70).sum()} of {len(report)}")
print(
    f"OF3 = UniProt sequence: {report['OF3 = UniProt sequence'].sum()} of {len(report)}"
)
display(report[~(report["pLDDT OF3"] >= 70) | ~report["OF3 = UniProt sequence"]])

       pLDDT OF3  pLDDT AF2
count      151.0      151.0
mean        73.3       87.6
std         10.7        8.9
min         38.9       39.7
25%         67.6       84.4
50%         73.5       89.8
75%         80.6       93.8
max         94.1       98.3

OF3 pLDDT >= 70: 101 of 151
OF3 = UniProt sequence: 151 of 151

,uniprot_id,OF3 = UniProt sequence,MSA depth,confidence,pLDDT OF3,pLDDT AF2
0,A0A0B7GU52,True,101 + 87,0.3,68.9,78.3
3,E0SM38,True,101 + 101,0.3,69.6,87.4
4,O14561,True,101 + 101,0.2,65.6,77.7
5,O14625,True,101 + 105,0.3,64.2,80.0
7,O15392,True,101 + 101,0.2,56.5,94.8
10,O95166,True,101 + 101,0.3,57.6,94.9
11,O95994,True,101 + 110,0.3,65.5,86.2
16,P01215,True,101 + 73,0.2,69.6,91.8
19,P02283,True,102 + 106,0.2,53.3,84.4
20,P02721,True,101 + 101,0.1,55.8,83.4
22,P02947,True,101 + 101,0.2,69.2,70.4
25,P04908,True,103 + 101,0.2,48.8,90.8
26,P04972,True,101 + 48,0.1,50.8,66.4
27,P05019,True,101 + 101,0.1,60.9,59.5
29,P06702,True,101 + 101,0.2,56.9,94.3
30,P06899,True,101 + 104,0.2,50.8,85.5
42,P0A937,True,101 + 101,0.3,64.5,91.6
49,P0AE60,True,101 + 68,0.3,69.0,73.7
53,P0CH43,True,5 + 1,0.3,64.3,84.9
55,P0DP23,True,137 + 101,0.3,61.0,85.2
56,P0DP29,True,137 + 101,0.3,61.0,85.0
60,P13402,True,101 + 101,0.2,68.6,74.2
61,P13500,True,101 + 101,0.3,65.6,87.0
62,P13987,True,101 + 101,0.3,64.4,79.3
70,P23528,True,101 + 102,0.2,48.6,87.6
72,P25337,True,101 + 101,0.3,62.8,88.4
78,P35225,True,101 + 17,0.3,67.6,85.6
80,P41567,True,102 + 101,0.2,51.9,80.5
82,P47813,True,101 + 101,0.3,66.2,77.9
91,P61077,True,102 + 102,0.3,53.9,96.4
94,P62799,True,101 + 109,0.2,56.3,89.5
96,P62837,True,102 + 103,0.3,58.0,96.5
99,P63165,True,101 + 101,0.2,58.5,78.3
101,P63279,True,101 + 101,0.3,56.8,97.3
103,P68699,True,101 + 101,0.3,66.7,91.9
107,P69541,True,101 + 101,0.2,68.2,76.2
109,P80098,True,101 + 101,0.3,64.6,85.0
111,P84051,True,104 + 101,0.2,53.2,93.0
115,Q06835,True,107 + 101,0.1,38.9,91.6
118,Q15369,True,102 + 101,0.4,69.6,89.8
122,Q2RQ23,True,101 + 101,0.2,67.7,80.7
126,Q6Q547,True,101 + 102,0.2,60.1,93.7
127,Q6ZYL4,True,101 + 101,0.3,69.9,68.9
132,Q8LTJ5,True,5 + 6,0.3,62.0,56.9
138,Q99653,True,101 + 101,0.4,63.4,89.2
139,Q99731,True,101 + 103,0.3,66.0,83.2
140,Q9AZ42,True,7 + 76,0.3,58.5,94.7
144,Q9NYG5,True,101 + 101,0.3,68.2,92.4
145,Q9ULZ3,True,101 + 106,0.3,62.7,72.4
150,V9H5N5,True,13 + 17,0.4,69.2,39.7

---
**Next:** notebook 01 checks that every chosen structure is on disk and readable, and describes what
the set is; notebook 02 runs the comparisons.